# version: '3.9'
name: 'nuxt_pizza'
services:
  nuxt_pizza_db:
    image: postgres:17.2
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}
