# version: '3.9'
name: 'nuxt_pizza'
services:
  nuxt_pizza_db:
    image: postgres:17.2
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'nuxt_pizza'
    ports:
      - '5432:5432'
